config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  namespace :admin do
  resources :users
  end
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :expired_at, presence: true
  validates :status, presence: true
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  enum status: { 未着手: 0, 着手: 1, 完了: 2 }
  enum priority: { 低: 0, 中: 1, 高: 2 }
  scope :search_title, -> (search_title) { where("title LIKE ?", "%#{search_title}%") }
  scope :search_status, -> (search_status) { where(status: search_status)}
  scope :search_priority, -> (search_priority) { where(priority: search_priority)}
  scope :search_label, -> (search_label) { joins(:labels).where(labels: { id: search_label })}
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  has_secure_password
  has_many :tasks, dependent: :destroy
  enum admin: { 一般: false, 管理者: true }
  validates :password, presence: true, length: { minimum: 6 }
  validates :name,  presence: true, length: { maximum: 300 }
  validates :email, presence: true, length: { maximum: 300 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_destroy :lost_admin
  private
  def lost_admin
    if User.where(admin: true).count == 1 && self.admin == "管理者"
      throw(:abort)
    end
  end 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user,only: [:edit,:update,:destroy, :show]
  before_action :not_admin
  def index
    @users = User.select(:id,:name,:email)
  end

  def show
    @task = @user.tasks
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path notice: '新たな管理者が誕生しました'
    else
      render :new
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: '管理者を排除しました'
    else
      redirect_to admin_users_path, notice: '管理者は一人いないといけません'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: '管理者を更新しました'
    else
      render :edit
    end
  end

  def edit
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def not_admin
    redirect_to user_path(current_user.id), notice:"管理画面へは、管理者以外はアクセスできません"   unless current_user.admin == '管理者'
  end

  def user_params
    params.require(:user).premit(:admin,:name,:email,:password,:password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログインしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:sort_expired]
      # binding.irb
      @tasks = Kaminari.paginate_array(Task.all.order(endtime_at: :desc)).page(params[:page]).per(3)  
      
    elsif params[:sort_priority]
      # binding.irb 
      @tasks = Kaminari.paginate_array(current_user.tasks.order(priority: :desc)).page(params[:page]).per(3)
      
    elsif params[:search]
      # binding.irb
      if params[:task][:search_title].present? && params[:task][:search_status].present?
        # binding.irb
        @tasks = Kaminari.paginate_array(current_user.tasks.search_title(params[:search_title]).search_status(params[:search_status])).page(params[:page]).per(3)
        
      elsif params[:task][:search_title].present?
        # binding.irb
        @tasks = Kaminari.paginate_array(current_user.tasks.search_title(params[:task][:search_title])).page(params[:page]).per(3)
        
      elsif params[:task][:search_status].present?
        # binding.irb
        @tasks = Kaminari.paginate_array(current_user.tasks.search_status(params[:task][:search_status])).page(params[:page]).per(3)
        
      elsif params[:task][:search_priority].present?
        # binding.irb
        @tasks = Kaminari.paginate_array(current_user.tasks.search_priority(params[:task][:search_priority])).page(params[:page]).per(3)
      elsif params[:task][:search_label].present?
        # binding.irb
        @tasks = Kaminari.paginate_array(current_user.tasks.search_label(params[:task][:search_label])).page(params[:page]).per(3)
        
      else
        # binding.irb
        @tasks = Kaminari.paginate_array(current_user.tasks.order(id: :desc)).page(params[:page]).per(3)
        # @tasks << @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
      end
      
    else
      @tasks = Kaminari.paginate_array(current_user.tasks.order(id: :desc)).page(params[:page]).per(3)
      # @labels = Label.all
    end
  end  
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
        render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "タスクを作成しました"
      else
        render :new
      end
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task), notice: "タスクを更新しました"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "タスクを削除しました"
  end

  def show
  end

  def edit
  end

  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :expired_at, :status, :priority, :user_id,:user_id, {label_ids: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
    @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    # @task = Task.all
    @tasks = current_user.tasks
    # if @user.id != current_user.id
    #   redirect_to tasks_path
    # end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:admin,:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <div class="input_area">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, placeholder: "your user name" %>
    <br>
    <%= f.label :email %>
    <br>
    <%= f.email_field :email, placeholder: "your email" %>
    <br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, placeholder: "password" %>
    <br>
    <%= f.label :password_confirmation %>
    <br>
    <%= f.password_field :password_confirmation, placeholder: "type same password" %>
    <br>
    <%= f.label :admin %>
    <br>
    <%= f.select :admin, User.admins.keys %>
    <br>
    <%= f.submit yield(:button_text), class: 'button' %>
  </div>
<% end %> 

app/views/admin/users/edit.html.erb
<% provide(:button_text, '編集する')%>
<h1>管理者編集画面</h1>
<%= render 'form' %> 

app/views/admin/users/index.html.erb
<h1>管理者画面</h1>
<table border = "1" >

<th>ユーザーネーム</th>
<th>タスク数</th>
<th>詳細</th>
<th>編集</th>
<th>削除</th>
<% @users.each do |user| %>
<tr>
<td><%= user.name %></td>
<td><%= user.tasks.length %></td>
<td><%= link_to '詳細' ,admin_user_path(user.id) %></td>
<td><%= link_to '編集' ,edit_admin_user_path(user.id) %></td>
<td><%= link_to '削除' ,admin_user_path(user.id),method: :delete, data: { confirm: 'Are you sure?' }  %></td>
</tr>
<% end %>
</table>
<div class = "new_task_btn">
<button type="button" class="btn btn-default navbar-btn"><%= link_to '新たな管理者を作成する', new_admin_user_path %></button>
<button type="button" class="btn btn-default navbar-btn"><%= link_to '一般画面へ戻る', tasks_path %></button>
</div> 

app/views/admin/users/new.html.erb
<% provide(:button_text, '管理者作成')%>
<h1>新たな管理者作成ページ</h1>
<%= render 'form' %> 

app/views/admin/users/show.html.erb
<article class="admin_show">
  <h2>管理画面：ユーザー情報詳細</h2>
  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <section class="profile_block">
    <p><span class="item_name">ID</span> <%= @user.id %></p>
    <p><span class="item_name">名前</span> <%= @user.name %></p>
    <p><span class="item_name">メールアドレス</span> <%= @user.email %></p>
    <p><span class="item_name">管理権限</span> <%= @user.admin == "管理者" ? "あり" : "なし" %></p>
  </section>
  <ul class="tasklist">
    <% @tasks.each do |task| %>
    <li>
      <div class="upper">
        <p><span class="item_name">タスク名</span> <%= task.title %></p>
        <p><span class="item_name">内容</span> <%= task.content %></p>
      </div>
      <div class="lower">
        <p><span class="item_name">登録日時</span> <%= l task.created_at, format: :long %></p>
        <p><span class="item_name">終了期限</span> <%= l task.expired_at, format: :long %></p>
        <p><span class="item_name">ステータス</span> <%= task.status %></p>
        <p><span class="item_name">優先順位</span> <%= task.priority %></p>
        <div class="label_block">
          <% task.labels.each do |label| %>
            <span class="label label-success"><%= label.name %></span>
          <% end %>
        </div>
      </div>
      <div class="btns">
        <div class="innerblock">
          <%= link_to '詳細を確認する', task_path(task.id), class: "show_task" %>
          <%= link_to "タスクを編集する", edit_task_path(task.id), class: "edit_task" %>
          <%= link_to 'タスクを削除する', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "delete_task" %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
  <div class="pagination_block">
    <%= paginate @tasks %>
  </div>
  <p class="goto_back"><%= link_to "ユーザー一覧画面にもどる", admin_users_path %></p>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyouKadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "プロフィール", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "サインアップ", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
  <section class="form_block">
  <%= form_with(model: @task, local: true) do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>

    <div class="field">
      <%= form.label :expired_at %>
    <%= form.datetime_select :expired_at %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys %>
  </div>

  <div class="field">
      <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>

      <div class="actions">
          <%= form.submit %>
      </div>
    <% end %> 
  <p class="goto_back"><%= link_to "back to top", tasks_path %></p>
</section>

app/views/tasks/confirm.html.erb
<article class="task_confirm">
  <section class="form_block">
    <%= form_with(model: @task, url: tasks_path, local: true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :expired_at %>
      <%= form.hidden_field :status %>
      <%= form.hidden_field :priority %>

      <div class="field">
        <p>title</p>
        <p><span class="item_name">Task_Name</span> <%= @task.title %></p>
      </div>
      
      <div class="field">
        <p>Content</p>
        <p><span class="item_name">Content</span> <%= @task.content %></p>
      </div>

      <div class="field">
        <p><span class="item_name">Expiration</span> <%= l @task.expired_at, format: :long %></p>
      </div>

      <div class="field">
        <p><span class="item_name">Status</span> <%= @task.status %></p>
      </div>
      
      <div class="field">
        <p><span class="item_name">Priority</span> <%= @task.priority %></p>
      </div>
    
      <div class="actions">
        <%= form.submit  "submit" %>
        <%= form.submit "back", name: 'back' %>
      </div>
    <% end %>
  </section>
</article>

app/views/tasks/edit.html.erb
<article class="task_edit">
  <h2>タスクを編集する</h2>
  <%= render 'form' %>
</article>

app/views/tasks/index.html.erb
<article class="tasks_index">
  <h1>タスク一覧</h1>
  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>

  <div class="task_nav">
    <p class="sort_expired flex">
      <%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
      <%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %>
      <%= link_to "登録日が新しい順に戻す", tasks_path %>
    </p>
    <div class="search_box" >
      <%= form_with(model: Task.new, local: true, method: :get, url: tasks_path ) do |form| %>
        <%= form.label :search_title, "タスク名" %>
        <%= form.text_field :search_title, placeholder: "タスク名で検索" %>
        <%= form.label :search_status, "ステータス" %>
        <%= form.select :search_status, Task.statuses.keys, { include_blank: '選択して下さい'}, id: 'search_status' %>
        <%= form.label :search_priority, "優先順位" %>
        <%= form.select :search_priority, Task.priorities.keys, { include_blank: '選択して下さい'}, id: 'search_priority' %>
        <%= form.label :search_label, "ラベル" %>
        <%= form.select :search_label, Label.pluck(:name, :id), { include_blank: '選択してください' } %></p>
        <%= form.submit "検索", name: "search" %>
      <% end %>
    </div>
  </div>

  <ul class="tasklist">
    <% @tasks.each do |task| %>
      <li>
      <p>
          <span class="item_name">
            ユーザ名
          </span>
          <div class="item_name tasks-index_item_user_name" id=<%= "tasks-index_item_user_name-#{task.id}" %>>
            <%= task.user.name %>
          </div>
          </p>
        <p>
          <span class="item_name">
            タスク名
          </span>
          <div class="item_name tasks-index_item_title" id=<%= "tasks-index_item_title-#{task.id}" %>>
            <%= task.title %>
          </div>
        </p>
        <p>
          <span class="item_name">
            内容
          </span>
          <div class="item_name tasks-index_item_content" id=<%= "tasks-index_item_content-#{task.id}" %>>
            <%= task.content %>
          </div>
        </p>
        <p>
          <span class="item_name">
            登録日
          </span>
          <div class="item_name tasks-index_item_created_at" id = <%= "tasks-index_item_created_at-#{task.id}" %>>
            <%= l task.created_at, format: :long %>
          </div>
        </p>
        <p>
          <span class="item_name">
            終了期限
          </span>
          <div class="item_name tasks-index_item_expired_at" id=<%= "tasks-index_item_expired_at-#{task.id}" %>>
            <%= l task.expired_at, format: :long %>
          </div>
        </p>
        <p>
          <span class="item_name">
            ステータス
          </span>
          <div class="item_name tasks-index_item_status" id=<%= "tasks-index_item_status-#{task.id}" %>>
            <%= task.status %>
          </div>
          </p>
        <p>
          <span class="item_name">
            優先順位
          </span>
          <div class="item_name tasks-index_item_priority" id=<%= "tasks-index_item_priority-#{task.id}" %>>
            <%= task.priority %>
          </div>
          </p>
          
          <div class="label_block">
          <% task.labels.each do |label| %>
            <span><%= label.name %></span>
          <% end %>
        </div>

        <p class="btns">
          <%= link_to '詳細', task_path(task.id) %>
          <%= link_to '編集', edit_task_path(task.id), class: "edit_task" %>
          <%= link_to '削除', task_path(task.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </li>
    <% end %>
  </ul>
    <div class="pagination_block">
    <%= paginate @tasks %>
  </div>
  <p class="task_new"><%= link_to 'タスク作成', new_task_path %></p>
</article>

app/views/tasks/new.html.erb
<article clsss="tasks_new">
  <h1>New Task</h1>
  <%= render 'form', task: @task %>
  <%= link_to 'Back', tasks_path %>
</article>

app/views/tasks/show.html.erb
<article class="tasks_show">
  <h2>タスク詳細</h2>
  <ul class="tasklist">
    <li>
      <p><strong>Task_Name:</strong></p>
      <p><%= @task.title %></P>

      <p><strong>Content:</strong></p>
      <p><%= @task.content %></p>

      <p><span class="item_name">Task_Name</span> <%= @task.title %></p>
      <p><span class="item_name">User_Name</span> <%= @task.user.name %></p>
      <p><span class="item_name">Content</span> <%= @task.content %></p>
      <p><span class="item_name">Submission_Date</span> <%= l @task.created_at %></p>
      <p><span class="item_name">Expiration_Date</span> <%= l @task.expired_at %></p>
      <p><span class="item_name">Status</span> <%= @task.status %></p>
      <p><span class="item_name">Priority</span> <%= @task.priority %></p>
      <div class="label_block">
          <% @task.labels.each do |label| %>
            <span class="label label-success"><%= label.name %></span>
          <% end %>
        </div>
    </li>
  </ul>
  <br>
  <p class="goto_back"><%= link_to 'Back', tasks_path %></p>
</article> 

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<article class="user_new">
  <h2>新規登録</h2>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <h3><%= @user.errors.count %>件のエラーがあります。</h3>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="form_block">
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </section>
</article>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to 'タスク作成', new_task_path %>
<%= link_to '戻る', tasks_path %>
<% @tasks.each do |task| %>
  <ul class="tasklist">
    <% @tasks.each do |task| %>
    <%# <tr class="task_row"> %>
      <li>
        <p>
          <span class="item_name">
            タスク名
          </span>
          <div class="item_name tasks-index_item_title" id=<%= "tasks-index_item_title-#{task.id}" %>>
            <%= task.title %>
          </div>
        </p>
        <p>
          <span class="item_name">
            内容
          </span>
          <div class="item_name tasks-index_item_content" id=<%= "tasks-index_item_content-#{task.id}" %>>
            <%= task.content %>
          </div>
        </p>
        <p>
          <span class="item_name">
            登録日
          </span>
          <div class="item_name tasks-index_item_created_at" id = <%= "tasks-index_item_created_at-#{task.id}" %>>
            <%= l task.created_at, format: :long %>
          </div>
        </p>
        <p>
          <span class="item_name">
            終了期限
          </span>
          <div class="item_name tasks-index_item_expired_at" id=<%= "tasks-index_item_expired_at-#{task.id}" %>>
            <%= l task.expired_at, format: :long %>
          </div>
        </p>
        <p>
          <span class="item_name">
            ステータス
          </span>
          <div class="item_name tasks-index_item_status" id=<%= "tasks-index_item_status-#{task.id}" %>>
            <%= task.status %>
          </div>
          </p>
        <p>
          <span class="item_name">
            優先順位
          </span>
      </li>
    <% end %>
  </ul>
<%end%>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>